version: '3'
services:
  cppdev:
    build:
      context: .
      dockerfile: Dockerfile
    image: cppdev
    container_name: cppdev
    volumes:
      -  ../://home/docker/cppdev
    stdin_open: true
    tty: true
    working_dir: /home/docker/cppdev