version: '3'
services:
  golangdev:
    build:
      context: .
      dockerfile: Dockerfile
    image: golangdev
    container_name: golangdev
    volumes:
      -  ../://home/docker/golangdev
    stdin_open: true
    tty: true
    working_dir: /home/docker/golangdev